### ISSUE TITLE
Incomplete?

### ISSUE THREAD

**Issue by kmpaul** [ncar-hackathons/cookiecutter-project-template#3]
Comparing what is in the `scientific-python` and `general-python` repos, it looks like a lot of the CircleCI stuff is missing from the cookiecutter.  Is the cookiecutter not the right way to create a new repo?  How do we keep all of these repos updated with all of the right features automatically?

**Comment by andersy005** [comment]
Are you referring to this circleCI setup: https://github.com/ncar-hackathons/cookiecutter-project-template/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D/.circleci?

or this one https://github.com/ncar-hackathons/cookiecutter-project-template/tree/master/.circleci?

**Comment by kmpaul** [comment]
Ah!  You are correct.  I was looking at the wrong CircleCI config file.  Thanks!
